pull_request_rules:
  # membuat requirement dari automerge dengan sistem
  # ketika workflow build passed maka akan dicentang
  # ketika target pull request ke main maka akan dicentang
  # ketika dikasih label 'ready-to-merge' akan dicentang

  # ketika requirement telah terpenuhi maka bot akan bekerja
  # dan pull request secara otomatis akan merge
  - name: ci testing kalo sukses ke squash dengan label
    conditions:
      - base=main
      - label=ready-to-merge
    actions:
      # menambahkan komentar jika sudah di merge
      comment:
        message: terima kasih atas kontribusinya @{{author}}!
      # menambahkan label jika sudah di merge
      label:
        add:
          - sudah dirieview!
      # metode sistem dari automerge
      merge:
        method: squash